### ISSUE TITLE
Subset Font Embedding

### ISSUE THREAD

**Issue by mbiegert** [hand-dot/labelmake#17]
Hey! Thanks for this awesome library. Unfortunately there's a bug in fontkit when subset embedding certain fonts. I've created an issue on the "pdf-lib" repository (https://github.com/Hopding/pdf-lib/issues/664) but it looks like it's not likely to be fixed anytime soon. Could you provide an option to not subset the font when embedding it? That would really help us out.

**Comment by hand-dot** [comment]
@mbiegert 
Thanks for reporting the bug!
I see.
I'll look into making it possible to specify a subset of options when embedding the font.

Like this?
```
  const option = { subset:false };
  const pdf = await labelmake({ template, inputs, font, option });

```

I hope to release a new version at the end of this week.

**Comment by mbiegert** [comment]
That would be very cool. I've made a small fork for our project that just disables subsetting alltogether. But an option is much better.

Maybe you could allow specifying per font if you want to subset it? So something like this for the font property:
```
font: {
  [key: string]: [Buffer | string | whatever, boolean];
}
```

Or in a non tuple way make it as an object:
```
font: {
  [key: string]: {
    fontBytes: Buffer | string | whatever;
    subset: boolean;
  }
}
```

**Comment by hand-dot** [comment]
@mbiegert 
Thank you for your reply.
> Maybe you could allow specifying per font if you want to subset it? 

Hmm... I know what you're thinking, but I like the current type of font object. I want to keep it as simple as possible.
What do you think?

**Comment by mbiegert** [comment]
Hm, then I see two options, either use the tuple method with the tuple being optional, like `[key: string]: FontObject | [ FontObject, boolean ]` (where "FontObject is just to abbreviate `Buffer | string | whatever` that can be used as font bytes).
Otherwise I only see you possibility with not being able to specify this per font or have the options object have another font object with keys that correspond to the font names, like
```
options: {
  font: {
    [key: string]: {
      subset: false;
      //... some other options for fonts(?)
    }
  }
}
```

I think it would be simpler to supply font options in the font object itself. (The non tuple way I suggested first.)

**Comment by hand-dot** [comment]
@mbiegert 
Sorry for the delay in replying.
I would like to implement it with a type such that in addition to the current font object type, a subset can also be specified.
I will be committed tomorrow!

```
font?: { [key: string]: string | Uint8Array | ArrayBuffer | {data: string | Uint8Array | ArrayBuffer; subset: boolean} }
```

**Comment by hand-dot** [comment]
Released in 2.0.9 version!

You can specify a subset with the following code

```
  const inputs = [
    { field1: "SauceHanSansJP", field2: "SauceHanSerifJP" },
  ];
  const template: Template = {
    basePdf: { height: 297, width: 210 },
    schemas: [
      {
        field1: {
          type: "text",
          position: { x: 30, y: 30 },
          width: 100,
          height: 20,
          fontName: "SauceHanSansJP",
        },
        field2: {
          type: "text",
          position: { x: 60, y: 60 },
          width: 100,
          height: 20,
          fontName: "SauceHanSerifJP",
        },
      },
    ],
  };

  const pdf = await labelmake({
    inputs,
    template,
    font: {
      SauceHanSansJP: {
        data: fs.readFileSync(__dirname + `/fonts/SauceHanSansJP.ttf`),
        subset: false,
      },
      SauceHanSerifJP: {
        data: fs.readFileSync(__dirname + `/fonts/SauceHanSerifJP.ttf`),
        subset: false,
      },
    },
  });
```

@mbiegert 
Could you check if it works correctly in your case?

**Comment by mbiegert** [comment]
> 
> @mbiegert
> Could you check if it works correctly in your case?

:tada: I'll check it out as soon as possible.

**Comment by mbiegert** [comment]
Sorry it took me so long, finally got around to test it and it works great! Thanks a lot.
