### ISSUE TITLE
Error: WinAnsi cannot encode

### ISSUE THREAD

**Issue by sito1912** [hand-dot/labelmake#19]
初めまして。
こちらのライブラリを利用させていただきたく[デモページ](https://labelmake.jp/javascript-pdf-generator-library/)を拝見しましたが、日本語を扱うと以下のエラーが出力されます。
```
Uncaught (in promise) Error: WinAnsi cannot encode "あ"
```
APIリファレンスを参考に、以下のようにArrayBufferをパラメータに与えても同様のエラーが発生するのですが、日本語フォントには対応していますでしょうか？
もしこちらの実装方法に誤りがありましたら、ご教示いただけますと幸いです。
```
const font = await fetch("https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf").then((res) => res.arrayBuffer())
const pdf = await labelmake({ template, inputs, font });
```

**Comment by hand-dot** [comment]
@sito1912 
はじめまして。

ライブラリは日本語に対応しています。
確認したところ、下記のフォントデータに日本語が入っていないようです。(データサイズも27KBです) 
`https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf`

データを確認して再度試していただけますか？

**Comment by sito1912** [comment]
@hand-dot 提示例のフォントについて、初歩的なミスで申し訳ありません。
改めて日本語が含まれるttfファイルをいくつかローカルで用意して、同様に試してみましたがエラー内容は変わらずフォント自体も反映されていませんでした。

そこで過去のIssue https://github.com/hand-dot/labelmake/issues/17#issuecomment-732705983 を確認して、subsetをfalseにすることで正しく出力することができました。
ご対応いただきありがとうございます。
本Issueはクローズとさせていただきます。
