### ISSUE TITLE
basePDFの回転(縦・横）について

### ISSUE THREAD

**Issue by takalab** [hand-dot/labelmake#20]
はじめまして。
ベースとなるPDFが横向きなのですが、MACのプレビューや以下のサービスを利用中は横向きになっているのですが、実際にコードをコピーして、node上で実行すると縦（90度回転した状態）になってしまいます。
https://labelmake.jp/javascript-pdf-generator-library/template-design/
何かオプション指定などで、横向きにすることは可能でしょうか？

node: v10.21.0
labelmake: 2.0.14

**Comment by hand-dot** [comment]
@takalab 
はじめまして。
なるほど、こちらで再現確認したいのですがもし可能であれば問題のベースとなるPDFいだだけますか？
それがむずかしければどのような手順で作成したPDFなのか教えていただければこちらで作れる場合は作って試してみます

**Comment by hand-dot** [comment]
現状は横向きにするオプションなどは用意がありません。

**Comment by takalab** [comment]
早速のご回答ありがとうございます。
ベースのPDFは添付のPDFになります。こちらはWordファイルからLibreOffice(macOS)の印刷メニューからPDF出力したものになります。
[001.pdf](https://github.com/hand-dot/labelmake/files/5975812/001.pdf)

ただ、他の横向きのPDFを試してみたところ、横向きのまま正常に出力されたので色々と試してみましたところ、
作成後のPDFで『印刷方向』を変えたあとにPDF出力したところ問題なく出力出来ました。お騒がせ致しました。
![スクリーンショット_2021-02-13_23_14_19](https://user-images.githubusercontent.com/7687925/107852052-b3083d00-6e51-11eb-8aff-bc957ef19c7c.jpg)

**Comment by hand-dot** [comment]
@takalab 
印刷の設定だったのですね。
こちらのissueクローズします。
