### ISSUE TITLE
Template designer not loading saved json template

### ISSUE THREAD

**Issue by Borisss** [hand-dot/labelmake#21]
Hi, I wanted to load template I did yesterday and modify it slightly but opening it via Load button doesn't do anything and there is no error in the console.

https://labelmake.jp/javascript-pdf-generator-library/template-design/

**Comment by hand-dot** [comment]
@Borisss 
sampledata and columns should be corresponds with schemas.

However, in the case you reported, it was a bug in the UI of the template editor, so we fixed it.

**Comment by hand-dot** [comment]
@Borisss 
Sorry...
I had a mistake. so now, you can correct save and correct load.
Please try again.
