### ISSUE TITLE
Feature Resquest: Add SVG to PDF document

### ISSUE THREAD

**Issue by jaronwanderley** [hand-dot/labelmake#25]
It would be amazing if you could add vector svg to the document, as jsPDF does.

**Comment by hand-dot** [comment]
Thanks for the feedback.
I'll consider it.

**Comment by hand-dot** [comment]
labelmake will be archived, the new features will be handled in the  [pdfme](https://github.com/pdfme/pdfme) repository, so this issue will be closed.

I have already created an issue in pdfme that matches the request in this issue.
-> https://github.com/pdfme/pdfme/issues/29
