### ISSUE TITLE
Unable to insert image using Labelmake

### ISSUE THREAD

**Issue by tmaguire** [hand-dot/labelmake#32]
Unable to insert images using the image field property - no errors issued to the console, but supplying a base64 encoded PNG results in a corrupted PDF being generated.

**Comment by hand-dot** [comment]
Can you paste the base64 data of an image here?

**Comment by tmaguire** [comment]
@hand-dot example of the base64 is here:

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIsAAAA8CAYAAABW1kkyAAAJbElEQVR4Xu2deah1VRmHHzUyMctKrSxLMBqdKtDEIkEkKrIRS5u0TLOyHCocshFtLlKzgUqznG00LRsEU9EEtRwwTa1sIodCo6woigffF5abfe5d5+z9fZ57z1r/fN85d+919n7Xb7/jb717HdpoEqiUwDqVx7XDmgRoYGkgqJZAA0u1qNqBDSwNA9US6APLUcAHe2a4ATgX+CLg/3NsAHw6PhwM3FP96+3AFSWBSWA5APga8Jfibp4C7BKf/fsPgP8BDSwraslnv9hJYHk58MqOBvFXHgN8FngU8FrgV7P/dDtzpUlgWrB4fzsA3wY+HuanT7M8HDgI2AN4EnAh8AXgm8C/CiFtA2i6XhzffSfmvCY+e33bAu9Y4hjP3x14NfDHYu5NQjv+KOZUC7YxQAKzgGWj0C4uuovoIpQ+i5fjZ0HylVjA5wZ4XNgvx/X63VeBXwJfiu/2BTYutFYec3kcKzA95snA6wOEguls4K2AwMixM3AKoJa8YoCM2qnFk9sVhg7uJDPksQ8EPgI8NZ7mf3TA8jjgDODtwE9j8gcAHwIeBLwnvjseWBc4ELg7vtPM6UB/A/hWAOuO0D5/j2ME07HAf4G3FXP9CfDa/d6H4EjgiQGiv7UVHy6BWTSLv+qi+OSq+rtgcTFPBm4HPgxcD/ync6lPAE4PkPn0941nAueEBik1hse+LAD7CuBq4I3AawpTlCZIjZOabLi0FnyGWcCidvgksNUEsPwTeEkARVP0W+DHwNeBS8NneRbwQ+D5wCUT1kAwnggkIMrD/NvFwLPjfH9HbfauMEX+/XPAnsB1C77Go93+LGB5aPgYd4Z5SB/Ff8s8i/7FjsBLgeeFD3MC8G5g+85i993QNGBZH/gYcFfkiA4LMGum0nyNJrRFnWgWsGQ0pClSxdfkWfRZNBPHAC+KRe0zQ2otF10TpubRb9GR7TND749oSwc5TZP5n0OBj4Ymm2TiFnW9B933tGDJPIs+gYv/mx6wPCMWXC1jFJNDkyO4BIsL3Ofgmvg7LcLy85ZxcHW09yuc48dH9KPJ2y2u79eDpNNOvo8EpsngPg14IWBkkWGrk3U1y4Mjp/LY8Dl0cD33TcBFYYYsCXTDYs9TK/we2D+0S03onDeUUZogNVrS3JU5nbb0AyUwTW3oqqgNqR3UKDn6zJAZ3ky26XxaS9LhNJ9S+hBlUk4Q6gR/qigz9CXlDKt1sMv6VF6LGkXzZZLvuwNl007vSKBVnRskqiXQwFItqnZgA0vDQLUEGliqRdUObGBpGKiWQANLtajagQ0sDQPVEhgbLNZorAjLc7Eu9DPgpOCiJDfXmo9suw8EfcAK9GeAFwQ/5ejgyJS5E4lWfcy96httBw6XwJhgMTln7ce0vqw4k3hPj2zsTyKjakJOsHw/SFGSpG6L9L8cGv8mXVMOi2O94MFs2DKywxd76AxjgmXX4KfsDVxZXJhMNjOzZnQFTdIL3gJ8vtAiFijPDNpD0hY2j3rPcUHJHHq/7fwBEhgLLM7zvuCXmK6XEJVDGqasNbeRyJbrclHyuIdF4VCgpSmSW3tE8FJaUXDAQo9x6lhgyfqQBcBJQy6LhUIZcCVxKY/3WtQ+1nc0RVItpW865Kf8e4wbbnPMLoGxweKVLLfRbJJm8VyBJAfldcCfgVODm9KKgrOv8WhnjgWWdER36tmS0b3YpcCSOwd+DtwcOwK6WzxGu/k20XQSGAss/qoOrsw2HVe1Q+7TkdDklg8jJOkNS4HFeSRf66sYEf0hQmwZ+23czxIYEyyGt1Ii9TcEhttb3YqxT4TJ+jOaluXAIlFKtpxsPOcygmpjDiQwJli8HR1dWXSGzyblJCgZDhv6yqt1LAcWQSflUqadvov7gdqYAwmMDZYxbikjK+mV3WzuGPO3OWaUwDyCxSSe2171fUrC94y32E4bSwLzBBY3npljkf1vYm65EHwsGbR5KiUwT2CxkGhPGLdyyMx3J2MbcySBpcCSW0K3A94cEU7fpWdh8JYRK8NZmc5K83JO8RyJdPVeSi1YfOJtadHtRuD51n2s+fyigWX1AsU7qwGL4a/7e14VHQtKiZgLka/iPO5WHItz0tUsq3sVVsjd1YDF9hk6nnZ7MtlWDrO2OqIXRE6kBEsNEcq57BJ1SGw39bNtOtzeKiFqkhmaBKYGsjUIvBqwfALYLDoflKbIepC0BKvB7lB8Z7G4tUQoaQkC0HBZIpS5FTWYQ23WwLIGF3/aqWvAIqXRRoN2ZDKjavMcx6PDBNkGdcvojZKLW0uEkoIp/6XcO20GV+BIhmpgmXZF1+DxtWDJjgbnF6ZIQBgl2cnAsNdGOi7ujZVEKCmYOsam9bvOs2av5N12o6FmhtYgKCZNXQsWeSX6JjbhcWFlwrnQVobVAnsVYLk1vluOCGVvOf0Te+1mL7i8Tnkt1oesMelgN7DcD+Do/mQtWKQcaBbSFAkSU/LvjZS8nJPULAkWf2upLGzWgPrAog9j2wwB18AyB0CpDZ01B4IlObJyaQWEXZbknvw1CE8JlptC6yxHhErC1Kxm6KwoDZRtSzWDh48Yws/JMs3HZUyjWZIja2cnk3P6Jtn/ttQsaoJaIpTNgdxD9IYIv5VK8mI0PZMc3Oxkac84GzHneV3HeD6kvEquYhqweMvZT87/W/DLp7oLlloiVB4nuAyhr418i1FXmRHu+iwZckuuMh/j3iOvwdzOIwrztUqWaT5uY1qwpCmS5mina7tDOrpg8bsaIlRqBOfSrG0aDZNt355mrc9n8bwtwjF2c5rEKncP2KTZ5oM2bO7rDDUfUl+hVzFPVecVKsLFuewGlsVZ68F32sAyWISLM0EDy+Ks9eA7XVtgce+QRUe3r7oXyGFbd7d62JvffreG426It/3p96KHbRYrjZbMEk9iz1mnsjquY2wZwTeNmGV2rvaeocEwuXeCtQEWoyL3E10WyT1/95ERKj8nNsz7MgabHgsagWE4LKnKFh2ZszH1nzmV7u27Kc2ODL5gQpK33BrLBQI0C58jiWxxp1kbYHGxfdItOJoPcZj5tR5UVpv93vcPqW3cZ+QLItxgluH67yb0aMmXPDwk3j8kwLwvw/GtW1+X8cBdgiVrNb46zi4HvkjBJ98tqdIQ3HusGfEJd5gttVa01NtWc8OYT3dmez23fF+RbxcpR/ZkcTN8nmONyDxMHxMvucJZlsi5/F4Wn12o2paSETDzf7exdVs7psRjAAAAAElFTkSuQmCC`
