### ISSUE TITLE
Option for include text false (barcode)

### ISSUE THREAD

**Issue by gary94746** [hand-dot/labelmake#33]
Hello,
When I use barcode there is not option for includeText false like bwibjs

**Comment by hand-dot** [comment]
@gary94746
Thanks for the suggestion.
Consider positively.

**Comment by hand-dot** [comment]
labelmake will be archived, the new features will be handled in the  [pdfme](https://github.com/pdfme/pdfme) repository, so this issue will be closed.

I have already created an issue in pdfme that matches the request in this issue.
-> https://github.com/pdfme/pdfme/issues/23
