### ISSUE TITLE
デザインツールはコードサンプルありますでしょうか？

### ISSUE THREAD

**Issue by muners** [hand-dot/labelmake#38]
こちらのツール非常に興味深く触らせていただいています。

https://labelmake.jp/javascript-pdf-generator-library/template-design/

こちらのデザインツールのサンプルコードなどはありますでしょうか？

**Comment by hand-dot** [comment]
現在その画面のコードは公開しておりませんが、下記のライブリを利用して構築しています
https://github.com/daybrush/moveable

**Comment by muners** [comment]
ありがとうございます、大変参考になります。

素晴らしいライブラリですね。
Feature Requestは私も非常にニーズがありますので、可能な範囲でぜひお願いしますｍ
