### ISSUE TITLE
Feature Request: Inserting circles, lines.

### ISSUE THREAD

**Issue by RyuNIshimura** [hand-dot/labelmake#43]
I would like to be able to add checks, enclosures, etc. to PDF items from boolean values, etc.
For this purpose, I was hoping to have the ability to add circles and lines by specifying their coordinates.
(You may be able to use images instead).

**Comment by hand-dot** [comment]
I think it's a great feature.
However, at this stage, I would like to keep the code simple, so please let me consider it.
