### ISSUE TITLE
Template design & code generator source

### ISSUE THREAD

**Issue by mmta41** [hand-dot/labelmake#48]
Hi, thank for your great work
do you have any plan to open source the code generator?

**Comment by drizzt00s** [comment]
hello, about this lib, Could I see edit panel if I run it successfully?

**Comment by hand-dot** [comment]
@drizzt00s 
Can you be a little more specific about what happened?

**Comment by hand-dot** [comment]
@mmta41 
Hi, I created new lib which has a Template design UI.
You can access bellow link.
https://github.com/pdfme/pdfme
