### ISSUE TITLE
compatibility with node >14

### ISSUE THREAD

**Issue by dartess** [hand-dot/labelmake#54]
Hi!

How you have

```
  "engines": {
    "node": "14.x"
  },
```

Does this mean that the package is incompatible with other versions? 

If not, is it possible to replace the entry with ">=14" or at least "14.x 16.x"?

**Comment by hand-dot** [comment]
@dartess 
Hi

I've only tested it on node14, so that's how I've described it.

**Comment by dartess** [comment]
@hand-dot
Are there any plans to test in other versions? Do you need any help with this?

_It also seems to me that the likelihood of a lack of backward compatibility in new releases of Node.js now is extremely small. Therefore, specifying the version as ">=14" seems perfectly acceptable. The worst that can happen is that the library users open the issue with the problem. At the same time, now more and more new users will come from version 16, which is LTS now. And they will receive a version mismatch warning on installation, although the library itself will most likely work correctly. Also, all users who plan to use the library in a browser receive a false message about incompatibility. But this is just my opinion, I do not impose it and is ready to help with testing if necessary._

**Comment by hand-dot** [comment]
@dartess 
Thank you!
I understand.
I'll run the tests on node 16 and if there are no problems, I'll release with the new minor change version within a few days.

**Comment by hand-dot** [comment]
@dartess 
Published as Version 2.0.20!

Thanks for the suggestion!
