### ISSUE TITLE
Feature Request: Able to change font weight

### ISSUE THREAD

**Issue by normanwongcl** [hand-dot/labelmake#55]
I would like to be able to change the font weight of the font that I am using.

![font weight](https://user-images.githubusercontent.com/34085667/142578913-b23fdd71-7cd9-4566-93fe-590f9598df1b.PNG)

**Comment by hand-dot** [comment]
@normanwongcl 

Thanks for the suggestion.
Consider positively.

**Comment by normanwongcl** [comment]
Duplicate of #30

**Comment by hand-dot** [comment]
this issue is Duplicate of #30

so i'll close.
