### ISSUE TITLE
cannot see edit panel

### ISSUE THREAD

**Issue by drizzt00s** [hand-dot/labelmake#58]
hi, I have my own case running successfully, but on the page I cannot see the edit panel. 

- [ ] 

- [ ]

**Comment by hand-dot** [comment]
Please check bellow issue.
https://github.com/hand-dot/labelmake/issues/48

**Comment by drizzt00s** [comment]
thanks for the reply. My understanding is that I cannot see and use edit panel until you open source the code generator. Am I correct?

**Comment by hand-dot** [comment]
Yes, correct.
