### ISSUE TITLE
About generating PDF file name automatically.

### ISSUE THREAD

**Issue by eg2data** [hand-dot/labelmake#62]
Hi, I really want to appreciate your help last time(#59).
I'd like to share my current point that I've been curious about and get your tips if possible. 

The point is about generating Pdf file name depending on the request.
Do you think it is possible to change Pdf file name in accordance with changes that I intend to?

For example, in my code, the file name is fixed as "index(1, 2, ......).pdf".
My intention is to generate Pdf files having different name, every time to do "npm run generatePdf.js", automatically.

If you think the question above is not defined clearly, please feel free to require me more information. 
Thanks!

![스크린샷 2021-12-26 11 11 55](https://user-images.githubusercontent.com/82001435/147397188-282a4935-1907-4654-9595-713f62b5b9c7.png)

**Comment by eg2data** [comment]
You can check the code at:
https://github.com/eg2data/chart_pdf_labelmake_2

**Comment by hand-dot** [comment]
@eg2data 
Hi, sorry i don't know, because this problem is not about this library.
but you can use uuid library for filename.
