### ISSUE TITLE
export types

### ISSUE THREAD

**Issue by dartess** [hand-dot/labelmake#66]
to use some types, you have to import them from dist, which is not correct.

eg:
```
import type { TemplateSchema } from 'labelmake/dist/types/type';
```

Could you export the utility types outside so they can be used?

Personally, types `TemplateSchema` and `Template` are important to us.

**Comment by hand-dot** [comment]
labelmake will be archived, the new features will be handled in the [pdfme](https://github.com/pdfme/pdfme) repository, so this issue will be closed.

if you use [@pdfme/generator](https://pdfme.com/docs/getting-started#generator), you can import TemplateSchema(Schema) like this.
```ts
import { generate, Schema, Template } from "@pdfme/generator";
```
