### ISSUE TITLE
Translate to JPG

### ISSUE THREAD

**Issue by eg2data** [hand-dot/labelmake#69]
Hi, I am much obliged to you for developing this kind of library.
It is very useful to make PDF from JS.

I have a question.
Can the library generate .jpg file through your library instead of PDF?
Sometimes my user requires the document with jpg type..!

Best wishes.

**Comment by hand-dot** [comment]
Hi!

It is not possible to create a JPG with labelmake.
However, PDFjs can be used to convert PDFs to images.
Please refer to the code below.
https://github.com/pdfme/pdfme/blob/47a0e7ac9003c819bb2a3d6a8dcff23dbd620caa/packages/ui/src/helper.ts#L283

By the way, labelmake will be archived in the future.
Instead, we are currently developing the following library. You can use this library if you like!
https://pdfme.com/
